### ISSUE TITLE
Boston dataset is not available anymore

### ISSUE THREAD

**Issue by sharepointmike** [lynstanford/Python-for-Data-Science-for-Dummies-2#2]
Hi, I try to follow the examples but the Boston dataset is not available anymore.
Can this be replaced by something else? Or can we get the boston dataset in another way?

**Comment by lynstanford** [comment]
Hi sharepointmike. Try the following links at Kaggle: https://www.kaggle.com/datasets/altavish/boston-housing-dataset. Another would be: https://www.kaggle.com/code/prasadperera/the-boston-housing-dataset/data.

The following python command will not work as 'The Boston Dataset' has been deprecated from the scikit-learn library: `from sklearn.datasets import load_boston`
Try this code instead: 

```
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2, 2]

print(X)
```

Or alternatively:

```
import warnings
from sklearn.datasets import load_boston
with warnings.catch_warnings():
    # You should probably not use this dataset.
    warnings.filterwarnings("ignore")
    X, y = load_boston(return_X_y=True)
print(X)
```

You can try loading the data directly from: http://lib.stat.cmu.edu/datasets/boston locally onto your machine before manipulating it.

**Comment by lynstanford** [comment]
Also, I am editing the notebook for you to follow along and will commit any changes.

**Comment by sharepointmike** [comment]
Great, thanks a lot!
